#!/usr/bin/env bash
# Downloads OpenOneRec/OneRec-8B-pro from the Hugging Face Hub into
# $MODEL_DIR, and prints the key architecture facts (context length, dtype,
# param count) that the serving scripts and docs rely on.
set -uo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/env.sh"
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

# shellcheck disable=SC1091
source "${VENV_DIR}/bin/activate"

mkdir -p "$MODEL_DIR"

log_info "Model: ${MODEL_ID} (revision: ${MODEL_REVISION})"
log_info "Target dir: ${MODEL_DIR}"
log_info "HF cache: ${HF_HOME}"

if [[ -n "${HF_TOKEN}" ]]; then
  huggingface-cli login --token "$HF_TOKEN" --add-to-git-credential >/dev/null 2>&1 || true
fi

# OneRec-8B-pro is public (apache-2.0, gated=false) as of the time this
# toolkit was written, so HF_TOKEN is optional. It's still wired through in
# case that changes or you swap MODEL_ID for a gated model.
retry 3 hf download "$MODEL_ID" \
  --revision "$MODEL_REVISION" \
  --local-dir "$MODEL_DIR" \
  || die "Model download failed after retries."

log_ok "Download complete."
du -sh "$MODEL_DIR"

log_info "Inspecting config.json for serving-relevant parameters..."
python3 - "$MODEL_DIR" <<'PYEOF'
import json, sys, pathlib

model_dir = pathlib.Path(sys.argv[1])
cfg_path = model_dir / "config.json"
if not cfg_path.exists():
    print("WARNING: config.json not found; cannot introspect model.")
    sys.exit(0)

cfg = json.loads(cfg_path.read_text())
fields = [
    "model_type", "architectures", "hidden_size", "num_hidden_layers",
    "num_attention_heads", "num_key_value_heads", "max_position_embeddings",
    "vocab_size", "torch_dtype", "rope_theta", "sliding_window",
]
print("-" * 60)
for f in fields:
    if f in cfg:
        print(f"  {f:28s}: {cfg[f]}")
print("-" * 60)

max_pos = cfg.get("max_position_embeddings")
out_dir = model_dir.parent.parent / "model_facts.env"
with open(out_dir, "w") as fh:
    fh.write(f"# Auto-generated by 02_download_model.sh on introspecting {model_dir}\n")
    if max_pos:
        # Leave headroom; recommend min(native context, 8192) as a sane
        # default benchmark context -- override in configs/matrix.yaml.
        fh.write(f"export MODEL_NATIVE_MAX_POSITION_EMBEDDINGS={max_pos}\n")
    fh.write(f"export MODEL_TORCH_DTYPE={cfg.get('torch_dtype', 'bfloat16')}\n")
print(f"Wrote model facts to {out_dir}")
PYEOF

deactivate

echo "=================================================================="
log_ok "Model ready at ${MODEL_DIR}"
log_info "Next: ./scripts/10_serve_vllm.sh   (or 11_serve_sglang.sh / 12_serve_trtllm.sh)"
log_info "Or just run the full matrix: ./run_all.sh"
echo "=================================================================="
